export const CREATE_JOBS_SUCCESS = "CREATE_JOBS_SUCCESS";
export const LOAD_JOBS_SUCCESS = "LOAD_JOBS_SUCCESS";
export const DELETE_JOBS_SUCCESS = "DELETE_JOBS_SUCCESS";
export const MODIFY_JOBS_SUCCESS = "MODIFY_JOBS_SUCCESS";
